# Generated by Django 5.0.1 on 2024-02-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0007_product_brand_product_item_form_product_net_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='net_quantity',
            field=models.CharField(choices=[('ml', 'Milliliters'), ('gm', 'Grams')], default='ml', max_length=6),
        ),
    ]
