# Generated by Django 5.0.1 on 2024-02-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0008_alter_product_net_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='net_quantity',
            field=models.CharField(max_length=20),
        ),
    ]
