# Generated by Django 5.0.1 on 2024-02-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0009_alter_product_net_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_form',
            field=models.CharField(choices=[('All', 'All'), ('Gel', 'Gel'), ('Cream', 'Cream'), ('Lotion', 'Lotion'), ('powder', 'powder'), ('tablets', 'tablets')], default='Gel', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='skin_type',
            field=models.CharField(choices=[('All', 'All'), ('Oily', 'Oily'), ('Dry', 'Dry'), ('Combination', 'Combination')], default='all', max_length=50),
        ),
    ]
